# Generated by Django 6.1.1 on 2026-10-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image for e-commerce', null=True, upload_to='product_images/'),
        ),
    ]
