# Generated by Django 6.1.1 on 2026-10-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('ZONE', 'Zone'), ('AISLE', 'Aisle'), ('RACK', 'Rack'), ('SHELF', 'Shelf'), ('BIN', 'Bin')], max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100, unique=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.storagelocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Specific bin/shelf location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_movements', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_movements', to='inventory.storagelocation'),
        ),
    ]
